namespace LazyEvo.LGrindEngine
{
    using DevComponents.DotNetBar;
    using DevComponents.DotNetBar.Controls;
    using DevComponents.Editors;
    using LazyEvo.LGrindEngine.Helpers;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    internal class Settings : Office2007Form
    {
        private IContainer components;
        private StyleManager styleManager1;
        private ButtonX SaveSettings;
        private GroupPanel groupPanel10;
        private GroupPanel groupPanel9;
        private CheckBoxX GrinderCBWaitForLoot;
        private CheckBoxX GrinderCBJumpRandomly;
        private CheckBoxX GrinderCBSkin;
        protected internal CheckBoxX GrinderCBStopLootOnFull;
        private CheckBoxX GrinderCBLoot;
        private GroupPanel groupPanel8;
        private LabelX labelX44;
        private IntegerInput GrinderIntSkipAddsDis;
        private LabelX labelX46;
        private LabelX labelX45;
        private IntegerInput GrinderIntAppRange;
        private IntegerInput GrinderIntSkipAddMaxCount;
        private CheckBoxX GrinderCBSkipPullOnAdds;
        private CheckBoxX UseMount;
        private GroupPanel groupPanel1;
        private CheckBoxX CBTrain;

        public Settings()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.styleManager1 = new StyleManager(this.components);
            this.SaveSettings = new ButtonX();
            this.groupPanel10 = new GroupPanel();
            this.UseMount = new CheckBoxX();
            this.groupPanel9 = new GroupPanel();
            this.GrinderCBWaitForLoot = new CheckBoxX();
            this.GrinderCBJumpRandomly = new CheckBoxX();
            this.GrinderCBSkin = new CheckBoxX();
            this.GrinderCBStopLootOnFull = new CheckBoxX();
            this.GrinderCBLoot = new CheckBoxX();
            this.groupPanel8 = new GroupPanel();
            this.labelX44 = new LabelX();
            this.GrinderIntSkipAddsDis = new IntegerInput();
            this.labelX46 = new LabelX();
            this.labelX45 = new LabelX();
            this.GrinderIntAppRange = new IntegerInput();
            this.GrinderIntSkipAddMaxCount = new IntegerInput();
            this.GrinderCBSkipPullOnAdds = new CheckBoxX();
            this.groupPanel1 = new GroupPanel();
            this.CBTrain = new CheckBoxX();
            this.groupPanel10.SuspendLayout();
            this.groupPanel9.SuspendLayout();
            this.groupPanel8.SuspendLayout();
            this.GrinderIntSkipAddsDis.BeginInit();
            this.GrinderIntAppRange.BeginInit();
            this.GrinderIntSkipAddMaxCount.BeginInit();
            this.groupPanel1.SuspendLayout();
            base.SuspendLayout();
            this.styleManager1.ManagerStyle = eStyle.Windows7Blue;
            this.SaveSettings.AccessibleRole = AccessibleRole.PushButton;
            this.SaveSettings.ColorTable = eButtonColor.OrangeWithBackground;
            this.SaveSettings.Location = new Point(0x9f, 0xef);
            this.SaveSettings.Name = "SaveSettings";
            this.SaveSettings.Size = new Size(0x65, 0x20);
            this.SaveSettings.Style = eDotNetBarStyle.StyleManagerControlled;
            this.SaveSettings.TabIndex = 0x8a;
            this.SaveSettings.Text = "Save and close";
            this.SaveSettings.Click += new EventHandler(this.SaveSettingsClick);
            this.groupPanel10.BackColor = Color.Transparent;
            this.groupPanel10.CanvasColor = SystemColors.Control;
            this.groupPanel10.ColorSchemeStyle = eDotNetBarStyle.Office2007;
            this.groupPanel10.Controls.Add(this.UseMount);
            this.groupPanel10.Location = new Point(0xd6, 0xb3);
            this.groupPanel10.Name = "groupPanel10";
            this.groupPanel10.Size = new Size(0xd5, 0x38);
            this.groupPanel10.Style.BackColor2SchemePart = eColorSchemePart.PanelBackground2;
            this.groupPanel10.Style.BackColorGradientAngle = 90;
            this.groupPanel10.Style.BackColorSchemePart = eColorSchemePart.PanelBackground;
            this.groupPanel10.Style.BorderBottom = eStyleBorderType.Solid;
            this.groupPanel10.Style.BorderBottomWidth = 1;
            this.groupPanel10.Style.BorderColorSchemePart = eColorSchemePart.PanelBorder;
            this.groupPanel10.Style.BorderLeft = eStyleBorderType.Solid;
            this.groupPanel10.Style.BorderLeftWidth = 1;
            this.groupPanel10.Style.BorderRight = eStyleBorderType.Solid;
            this.groupPanel10.Style.BorderRightWidth = 1;
            this.groupPanel10.Style.BorderTop = eStyleBorderType.Solid;
            this.groupPanel10.Style.BorderTopWidth = 1;
            this.groupPanel10.Style.Class = "";
            this.groupPanel10.Style.CornerDiameter = 4;
            this.groupPanel10.Style.CornerType = eCornerType.Rounded;
            this.groupPanel10.Style.TextAlignment = eStyleTextAlignment.Center;
            this.groupPanel10.Style.TextColorSchemePart = eColorSchemePart.PanelText;
            this.groupPanel10.Style.TextLineAlignment = eStyleTextAlignment.Near;
            this.groupPanel10.StyleMouseDown.Class = "";
            this.groupPanel10.StyleMouseDown.CornerType = eCornerType.Square;
            this.groupPanel10.StyleMouseOver.Class = "";
            this.groupPanel10.StyleMouseOver.CornerType = eCornerType.Square;
            this.groupPanel10.TabIndex = 0x8d;
            this.groupPanel10.Text = "Mount options";
            this.UseMount.BackColor = Color.Transparent;
            this.UseMount.BackgroundStyle.Class = "";
            this.UseMount.BackgroundStyle.CornerType = eCornerType.Square;
            this.UseMount.Location = new Point(3, 6);
            this.UseMount.Name = "UseMount";
            this.UseMount.Size = new Size(0x53, 0x17);
            this.UseMount.Style = eDotNetBarStyle.StyleManagerControlled;
            this.UseMount.TabIndex = 0x2f;
            this.UseMount.Text = "Use mount";
            this.groupPanel9.BackColor = Color.Transparent;
            this.groupPanel9.CanvasColor = SystemColors.Control;
            this.groupPanel9.ColorSchemeStyle = eDotNetBarStyle.Office2007;
            this.groupPanel9.Controls.Add(this.GrinderCBWaitForLoot);
            this.groupPanel9.Controls.Add(this.GrinderCBJumpRandomly);
            this.groupPanel9.Controls.Add(this.GrinderCBSkin);
            this.groupPanel9.Controls.Add(this.GrinderCBStopLootOnFull);
            this.groupPanel9.Controls.Add(this.GrinderCBLoot);
            this.groupPanel9.Location = new Point(4, 3);
            this.groupPanel9.Name = "groupPanel9";
            this.groupPanel9.Size = new Size(0xcc, 170);
            this.groupPanel9.Style.BackColor2SchemePart = eColorSchemePart.PanelBackground2;
            this.groupPanel9.Style.BackColorGradientAngle = 90;
            this.groupPanel9.Style.BackColorSchemePart = eColorSchemePart.PanelBackground;
            this.groupPanel9.Style.BorderBottom = eStyleBorderType.Solid;
            this.groupPanel9.Style.BorderBottomWidth = 1;
            this.groupPanel9.Style.BorderColorSchemePart = eColorSchemePart.PanelBorder;
            this.groupPanel9.Style.BorderLeft = eStyleBorderType.Solid;
            this.groupPanel9.Style.BorderLeftWidth = 1;
            this.groupPanel9.Style.BorderRight = eStyleBorderType.Solid;
            this.groupPanel9.Style.BorderRightWidth = 1;
            this.groupPanel9.Style.BorderTop = eStyleBorderType.Solid;
            this.groupPanel9.Style.BorderTopWidth = 1;
            this.groupPanel9.Style.Class = "";
            this.groupPanel9.Style.CornerDiameter = 4;
            this.groupPanel9.Style.CornerType = eCornerType.Rounded;
            this.groupPanel9.Style.TextAlignment = eStyleTextAlignment.Center;
            this.groupPanel9.Style.TextColorSchemePart = eColorSchemePart.PanelText;
            this.groupPanel9.Style.TextLineAlignment = eStyleTextAlignment.Near;
            this.groupPanel9.StyleMouseDown.Class = "";
            this.groupPanel9.StyleMouseDown.CornerType = eCornerType.Square;
            this.groupPanel9.StyleMouseOver.Class = "";
            this.groupPanel9.StyleMouseOver.CornerType = eCornerType.Square;
            this.groupPanel9.TabIndex = 140;
            this.groupPanel9.Text = "General";
            this.GrinderCBWaitForLoot.BackColor = Color.Transparent;
            this.GrinderCBWaitForLoot.BackgroundStyle.Class = "";
            this.GrinderCBWaitForLoot.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBWaitForLoot.Location = new Point(3, 0x20);
            this.GrinderCBWaitForLoot.Name = "GrinderCBWaitForLoot";
            this.GrinderCBWaitForLoot.Size = new Size(0xa2, 0x17);
            this.GrinderCBWaitForLoot.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBWaitForLoot.TabIndex = 11;
            this.GrinderCBWaitForLoot.Text = "Wait for loot";
            this.GrinderCBJumpRandomly.BackColor = Color.Transparent;
            this.GrinderCBJumpRandomly.BackgroundStyle.Class = "";
            this.GrinderCBJumpRandomly.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBJumpRandomly.Location = new Point(3, 0x77);
            this.GrinderCBJumpRandomly.Name = "GrinderCBJumpRandomly";
            this.GrinderCBJumpRandomly.Size = new Size(0xa2, 0x17);
            this.GrinderCBJumpRandomly.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBJumpRandomly.TabIndex = 10;
            this.GrinderCBJumpRandomly.Text = "Jump randomly";
            this.GrinderCBSkin.BackColor = Color.Transparent;
            this.GrinderCBSkin.BackgroundStyle.Class = "";
            this.GrinderCBSkin.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBSkin.Location = new Point(3, 90);
            this.GrinderCBSkin.Name = "GrinderCBSkin";
            this.GrinderCBSkin.Size = new Size(0xa2, 0x17);
            this.GrinderCBSkin.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBSkin.TabIndex = 8;
            this.GrinderCBSkin.Text = "Skin";
            this.GrinderCBStopLootOnFull.BackColor = Color.Transparent;
            this.GrinderCBStopLootOnFull.BackgroundStyle.Class = "";
            this.GrinderCBStopLootOnFull.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBStopLootOnFull.Location = new Point(3, 0x3d);
            this.GrinderCBStopLootOnFull.Name = "GrinderCBStopLootOnFull";
            this.GrinderCBStopLootOnFull.Size = new Size(0xa2, 0x17);
            this.GrinderCBStopLootOnFull.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBStopLootOnFull.TabIndex = 9;
            this.GrinderCBStopLootOnFull.Text = "Stop loot on full bags";
            this.GrinderCBLoot.BackColor = Color.Transparent;
            this.GrinderCBLoot.BackgroundStyle.Class = "";
            this.GrinderCBLoot.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBLoot.Location = new Point(3, 3);
            this.GrinderCBLoot.Name = "GrinderCBLoot";
            this.GrinderCBLoot.Size = new Size(0xa2, 0x17);
            this.GrinderCBLoot.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBLoot.TabIndex = 7;
            this.GrinderCBLoot.Text = "Loot";
            this.groupPanel8.BackColor = Color.Transparent;
            this.groupPanel8.CanvasColor = SystemColors.Control;
            this.groupPanel8.ColorSchemeStyle = eDotNetBarStyle.Office2007;
            this.groupPanel8.Controls.Add(this.labelX44);
            this.groupPanel8.Controls.Add(this.GrinderIntSkipAddsDis);
            this.groupPanel8.Controls.Add(this.labelX46);
            this.groupPanel8.Controls.Add(this.labelX45);
            this.groupPanel8.Controls.Add(this.GrinderIntAppRange);
            this.groupPanel8.Controls.Add(this.GrinderIntSkipAddMaxCount);
            this.groupPanel8.Controls.Add(this.GrinderCBSkipPullOnAdds);
            this.groupPanel8.Location = new Point(0xd6, 3);
            this.groupPanel8.Name = "groupPanel8";
            this.groupPanel8.Size = new Size(0xd5, 170);
            this.groupPanel8.Style.BackColor2SchemePart = eColorSchemePart.PanelBackground2;
            this.groupPanel8.Style.BackColorGradientAngle = 90;
            this.groupPanel8.Style.BackColorSchemePart = eColorSchemePart.PanelBackground;
            this.groupPanel8.Style.BorderBottom = eStyleBorderType.Solid;
            this.groupPanel8.Style.BorderBottomWidth = 1;
            this.groupPanel8.Style.BorderColorSchemePart = eColorSchemePart.PanelBorder;
            this.groupPanel8.Style.BorderLeft = eStyleBorderType.Solid;
            this.groupPanel8.Style.BorderLeftWidth = 1;
            this.groupPanel8.Style.BorderRight = eStyleBorderType.Solid;
            this.groupPanel8.Style.BorderRightWidth = 1;
            this.groupPanel8.Style.BorderTop = eStyleBorderType.Solid;
            this.groupPanel8.Style.BorderTopWidth = 1;
            this.groupPanel8.Style.Class = "";
            this.groupPanel8.Style.CornerDiameter = 4;
            this.groupPanel8.Style.CornerType = eCornerType.Rounded;
            this.groupPanel8.Style.TextAlignment = eStyleTextAlignment.Center;
            this.groupPanel8.Style.TextColorSchemePart = eColorSchemePart.PanelText;
            this.groupPanel8.Style.TextLineAlignment = eStyleTextAlignment.Near;
            this.groupPanel8.StyleMouseDown.Class = "";
            this.groupPanel8.StyleMouseDown.CornerType = eCornerType.Square;
            this.groupPanel8.StyleMouseOver.Class = "";
            this.groupPanel8.StyleMouseOver.CornerType = eCornerType.Square;
            this.groupPanel8.TabIndex = 0x8b;
            this.groupPanel8.Text = "Limits";
            this.labelX44.BackColor = Color.Transparent;
            this.labelX44.BackgroundStyle.Class = "";
            this.labelX44.BackgroundStyle.CornerType = eCornerType.Square;
            this.labelX44.Location = new Point(3, 3);
            this.labelX44.Name = "labelX44";
            this.labelX44.Size = new Size(0x5c, 0x17);
            this.labelX44.TabIndex = 0;
            this.labelX44.Text = "Approach range:";
            this.GrinderIntSkipAddsDis.BackgroundStyle.Class = "DateTimeInputBackground";
            this.GrinderIntSkipAddsDis.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderIntSkipAddsDis.ButtonFreeText.Shortcut = eShortcut.F2;
            this.GrinderIntSkipAddsDis.Location = new Point(110, 0x3d);
            this.GrinderIntSkipAddsDis.Name = "GrinderIntSkipAddsDis";
            this.GrinderIntSkipAddsDis.ShowUpDown = true;
            this.GrinderIntSkipAddsDis.Size = new Size(0x37, 20);
            this.GrinderIntSkipAddsDis.TabIndex = 4;
            this.labelX46.BackColor = Color.Transparent;
            this.labelX46.BackgroundStyle.Class = "";
            this.labelX46.BackgroundStyle.CornerType = eCornerType.Square;
            this.labelX46.Location = new Point(3, 0x54);
            this.labelX46.Name = "labelX46";
            this.labelX46.Size = new Size(0x5c, 0x17);
            this.labelX46.TabIndex = 5;
            this.labelX46.Text = "Max adds count:";
            this.labelX45.BackColor = Color.Transparent;
            this.labelX45.BackgroundStyle.Class = "";
            this.labelX45.BackgroundStyle.CornerType = eCornerType.Square;
            this.labelX45.Location = new Point(3, 0x3a);
            this.labelX45.Name = "labelX45";
            this.labelX45.Size = new Size(0x5c, 0x17);
            this.labelX45.TabIndex = 3;
            this.labelX45.Text = "Distance:";
            this.GrinderIntAppRange.BackgroundStyle.Class = "DateTimeInputBackground";
            this.GrinderIntAppRange.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderIntAppRange.ButtonFreeText.Shortcut = eShortcut.F2;
            this.GrinderIntAppRange.Location = new Point(110, 6);
            this.GrinderIntAppRange.Name = "GrinderIntAppRange";
            this.GrinderIntAppRange.ShowUpDown = true;
            this.GrinderIntAppRange.Size = new Size(0x37, 20);
            this.GrinderIntAppRange.TabIndex = 1;
            this.GrinderIntSkipAddMaxCount.BackgroundStyle.Class = "DateTimeInputBackground";
            this.GrinderIntSkipAddMaxCount.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderIntSkipAddMaxCount.ButtonFreeText.Shortcut = eShortcut.F2;
            this.GrinderIntSkipAddMaxCount.Location = new Point(110, 0x57);
            this.GrinderIntSkipAddMaxCount.Name = "GrinderIntSkipAddMaxCount";
            this.GrinderIntSkipAddMaxCount.ShowUpDown = true;
            this.GrinderIntSkipAddMaxCount.Size = new Size(0x37, 20);
            this.GrinderIntSkipAddMaxCount.TabIndex = 6;
            this.GrinderCBSkipPullOnAdds.BackColor = Color.Transparent;
            this.GrinderCBSkipPullOnAdds.BackgroundStyle.Class = "";
            this.GrinderCBSkipPullOnAdds.BackgroundStyle.CornerType = eCornerType.Square;
            this.GrinderCBSkipPullOnAdds.Location = new Point(3, 0x20);
            this.GrinderCBSkipPullOnAdds.Name = "GrinderCBSkipPullOnAdds";
            this.GrinderCBSkipPullOnAdds.Size = new Size(0xa2, 0x17);
            this.GrinderCBSkipPullOnAdds.Style = eDotNetBarStyle.StyleManagerControlled;
            this.GrinderCBSkipPullOnAdds.TabIndex = 2;
            this.GrinderCBSkipPullOnAdds.Text = "Skip mob with adds (pull)";
            this.groupPanel1.BackColor = Color.Transparent;
            this.groupPanel1.CanvasColor = SystemColors.Control;
            this.groupPanel1.ColorSchemeStyle = eDotNetBarStyle.Office2007;
            this.groupPanel1.Controls.Add(this.CBTrain);
            this.groupPanel1.Location = new Point(4, 0xb3);
            this.groupPanel1.Name = "groupPanel1";
            this.groupPanel1.Size = new Size(0xcc, 0x38);
            this.groupPanel1.Style.BackColor2SchemePart = eColorSchemePart.PanelBackground2;
            this.groupPanel1.Style.BackColorGradientAngle = 90;
            this.groupPanel1.Style.BackColorSchemePart = eColorSchemePart.PanelBackground;
            this.groupPanel1.Style.BorderBottom = eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderBottomWidth = 1;
            this.groupPanel1.Style.BorderColorSchemePart = eColorSchemePart.PanelBorder;
            this.groupPanel1.Style.BorderLeft = eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderLeftWidth = 1;
            this.groupPanel1.Style.BorderRight = eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderRightWidth = 1;
            this.groupPanel1.Style.BorderTop = eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderTopWidth = 1;
            this.groupPanel1.Style.Class = "";
            this.groupPanel1.Style.CornerDiameter = 4;
            this.groupPanel1.Style.CornerType = eCornerType.Rounded;
            this.groupPanel1.Style.TextAlignment = eStyleTextAlignment.Center;
            this.groupPanel1.Style.TextColorSchemePart = eColorSchemePart.PanelText;
            this.groupPanel1.Style.TextLineAlignment = eStyleTextAlignment.Near;
            this.groupPanel1.StyleMouseDown.Class = "";
            this.groupPanel1.StyleMouseDown.CornerType = eCornerType.Square;
            this.groupPanel1.StyleMouseOver.Class = "";
            this.groupPanel1.StyleMouseOver.CornerType = eCornerType.Square;
            this.groupPanel1.TabIndex = 0x8e;
            this.groupPanel1.Text = "Train options";
            this.CBTrain.BackColor = Color.Transparent;
            this.CBTrain.BackgroundStyle.Class = "";
            this.CBTrain.BackgroundStyle.CornerType = eCornerType.Square;
            this.CBTrain.Location = new Point(3, 6);
            this.CBTrain.Name = "CBTrain";
            this.CBTrain.Size = new Size(0x53, 0x17);
            this.CBTrain.Style = eDotNetBarStyle.StyleManagerControlled;
            this.CBTrain.TabIndex = 0x2f;
            this.CBTrain.Text = "Train";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(0xdf, 0xea, 0xf6);
            base.ClientSize = new Size(0x1b2, 0x112);
            base.Controls.Add(this.groupPanel1);
            base.Controls.Add(this.groupPanel10);
            base.Controls.Add(this.groupPanel9);
            base.Controls.Add(this.groupPanel8);
            base.Controls.Add(this.SaveSettings);
            this.DoubleBuffered = true;
            base.Name = "Settings";
            this.Text = "Settings";
            base.Load += new EventHandler(this.SettingsLoad);
            this.groupPanel10.ResumeLayout(false);
            this.groupPanel9.ResumeLayout(false);
            this.groupPanel8.ResumeLayout(false);
            this.GrinderIntSkipAddsDis.EndInit();
            this.GrinderIntAppRange.EndInit();
            this.GrinderIntSkipAddMaxCount.EndInit();
            this.groupPanel1.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        private void SaveSettingsClick(object sender, EventArgs e)
        {
            GrindingSettings.Skin = this.GrinderCBSkin.Checked;
            GrindingSettings.Loot = this.GrinderCBLoot.Checked;
            GrindingSettings.WaitForLoot = this.GrinderCBWaitForLoot.Checked;
            GrindingSettings.StopLootOnFull = this.GrinderCBStopLootOnFull.Checked;
            GrindingSettings.Jump = this.GrinderCBJumpRandomly.Checked;
            GrindingSettings.ApproachRange = this.GrinderIntAppRange.Value;
            GrindingSettings.SkipMobsWithAdds = this.GrinderCBSkipPullOnAdds.Checked;
            GrindingSettings.SkipAddsDistance = this.GrinderIntSkipAddsDis.Value;
            GrindingSettings.SkipAddsCount = this.GrinderIntSkipAddMaxCount.Value;
            GrindingSettings.Mount = this.UseMount.Checked;
            GrindingSettings.ShouldTrain = this.CBTrain.Checked;
            GrindingSettings.SaveSettings();
            base.Close();
        }

        private void SettingsLoad(object sender, EventArgs e)
        {
            GrindingSettings.LoadSettings();
            this.GrinderCBSkin.Checked = GrindingSettings.Skin;
            this.GrinderCBLoot.Checked = GrindingSettings.Loot;
            this.GrinderCBWaitForLoot.Checked = GrindingSettings.WaitForLoot;
            this.GrinderCBStopLootOnFull.Checked = GrindingSettings.StopLootOnFull;
            this.GrinderCBJumpRandomly.Checked = GrindingSettings.Jump;
            this.GrinderIntAppRange.Value = GrindingSettings.ApproachRange;
            this.GrinderCBSkipPullOnAdds.Checked = GrindingSettings.SkipMobsWithAdds;
            this.GrinderIntSkipAddsDis.Value = GrindingSettings.SkipAddsDistance;
            this.GrinderIntSkipAddMaxCount.Value = GrindingSettings.SkipAddsCount;
            this.UseMount.Checked = GrindingSettings.Mount;
            this.CBTrain.Checked = GrindingSettings.ShouldTrain;
        }
    }
}

